#!/usr/bin/env bash

host=$1
username=$2
echo "getting creds for $host and $username" >> /tmp/wtf.log
pass=$(emacsclient -e "(shahid/read-auth-passwd \"$host\" \"$username\")")
pass=${pass//\"/}
echo -n $pass
