#!/usr/bin/env bash

if [[ $# > 0 ]]; then
    if [[ $1 == /* ]]; then
        args=$1
    else
        args=$PWD/$1
    fi
fi

exec docker exec --detach-keys 'ctrl-z' -it emacs bash -c "stty cols $(tput cols) && stty rows $(tput lines) && emacsclient -t $args"
