;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        backward-up-list
        dabbrev-completion
        dabbrev-expand
        down-list
        downcase-region
        electric-newline-and-maybe-indent
        forward-sexp
        indent-for-tab-command
        kill-region
        kill-sexp
        mark-sexp
        markdown-outdent-or-delete
        org-delete-char
        orgtbl-self-insert-command
        parinfer-backward-delete-char
        parinfer-smart-tab:backward-char
        parinfer-smart-tab:forward-char
        parinfer-yank
        sh-assignment
        transpose-sexps
        transpose-words
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        completion-at-point
        end-of-buffer
        eshell
        handle-select-window
        helm-M-x
        mc-doit-mc/mark-next-like-this
        multiple-cursor-activate
        multiple-cursor-doit
        repeat
        ))
