;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        dabbrev-completion
        dabbrev-expand
        forward-sexp
        kill-region
        kill-sexp
        mark-sexp
        parinfer-backward-delete-char
        parinfer-smart-tab:backward-char
        parinfer-smart-tab:forward-char
        transpose-words
        ))

(setq mc/cmds-to-run-once
      '(
        completion-at-point
        helm-M-x
        mc-doit-mc/mark-next-like-this
        multiple-cursor-activate
        multiple-cursor-doit
        repeat
        ))
