#!/usr/bin/env bash

image="jvshahid/development"
docker pull $image
docker rm -f emacs
docker run -d --detach-keys 'ctrl-z' \
       --rm \
       --name emacs \
       -e PATH=$PATH \
       -e DISPLAY=$DISPLAY \
       -e HOME=$HOME \
       -e TERM=screen-256color \
       -v /tmp:/tmp \
       -v $HOME:$HOME \
       --user $UID:$UID \
       -it $image \
       --device /dev/snd \
       bash -c "/usr/local/bin/emacs --daemon & read"
