#!/usr/bin/env bash

image="jvshahid/development"
docker pull $image
docker rm -f emacs-$USER 2>/dev/null
docker run -d --detach-keys 'ctrl-z' \
       --rm \
       --name emacs-$USER \
       -e PATH=$PATH \
       -e DISPLAY=$DISPLAY \
       -e HOME=$HOME \
       -e TERM=screen-256color \
       -e LANG=en_US.UTF-8 \
       -v /tmp:/tmp \
       -v /dev:/dev \
       -v $HOME:$HOME \
       -v $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
       -e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
       -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
       --user $UID:$UID \
       -it $image \
       bash -c "/usr/local/bin/emacs --fg-daemon"
