#!/usr/bin/env bash

# scan codes:
#
# left alt 38 - b8
# left windows e05b - e08b
# left ctrl 1d - 9d
# caps lock 3a - ba
# right alt e038 - e0b8
# right ctrl e01d - e19d
# right prtscreen e037 ??????
#
# keycodes:
# windows: 125
# left ctrl: 29
# left alt: 56
# right ctrl: 97
# right alt: 100

# right prt scr should be right alt
# set prtsc to alt
sudo setkeycodes e037 100
# set alt-prtsc to be alt
sudo setkeycodes 54 100
# disable sysrq key
sudo setkeycodes e02a 0

# left alt should be left ctrl
sudo setkeycodes 38 29
# left windows should be left alt
sudo setkeycodes e05b 56
# capslock should be windows
sudo setkeycodes 3a 125
# right alt should be right ctrl
sudo setkeycodes e038 97
