(straight-use-package 'rust-mode)
(straight-use-package 'lsp-rust)
(autoload 'lsp-rust-enable "lsp-rust" "start lsp support for rust" t)
(add-hook 'rust-mode-hook (lambda ()
                            (lsp-rust-enable)
                            (flycheck-mode)
                            (yas-minor-mode)
                            (auto-complete-mode -1)
                            (company-mode)
                            (local-set-key (kbd "C-c C-j") 'xref-find-definitions)
                            (local-set-key (kbd "M-.") 'company-complete)))
